name: Factions
author: Tethered_, edited by VMPE Development Team
description: An imported factions plugin from the PC version of the game to pocket edition. [factions_pc]
version: 5.7.10
main: FactionsPro\FactionMain
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
softdepend: ["PureChat", "AntiSpamPro", "EssentialsPE", "EconomyAPI"]
commands:
  f:
    description: Faction commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
