name: FactionsPro
author: Tethered_, edited by VMPE Development Team
description: A Extended Factions plugin. [full-updates Branch]
version: 2.0.0-beta2
main: FactionsPro\FactionMain
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
softdepend: ["PureChat", "AntiSpamPro", "EssentialsPE", "EconomyAPI"]
commands:
  f:
    description: Faction commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
