name: FactionsPro
author: Tethered_, edited by VMPE Development Team
description: A Extended Factions plugin. [configurations-v2 branch]
version: 3.0.0-ALPHA3
main: FactionsPro\Main
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
softdepend: ["PureChat", "EconomyAPI", "AntiSpamPro", "EssentialsPE"]
commands:
  f:
    description: Faction commands.
    aliases: ["faction"]
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
